blank_issues_enabled: false
contact_links:
  - name: 🌐 aiVOLUTION Support & Knowledge Base
    url: https://www.aivolution.dk/xpander
    about: For licensing, general inquiries, or product documentation, visit our official support portal.
